/*
 * Do not remove this unless you get business authorization.
 * Copyright (c) 2016 - 2018 All Rights Reserved.
 * Powered By [stategen.dalgen]
 */
package com.mycompany.biz.dao.impl;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.dao.DataAccessException;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import org.stategen.framework.ibatis.util.PageQueryUtils;
import org.stategen.framework.lite.PageList;

import com.mycompany.biz.dao.UserRoleDao;
import com.mycompany.biz.domain.UserRole;

/**
 * UserRoleDao
 * <pre>
 * database table: user_role
 * database table comments: UserRole
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 *
 * 该类仅可以修改引用
 * </pre>
 */
public class UserRoleDaoImpl extends SqlDaoSupportBase implements UserRoleDao {

    /**
	 * 
	 * sql:insert into user_role ( create_time , update_time , delete_flag , id , user_id , role_id , role_type ) VALUES (CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6),0,?,?,?,?)
	 */
    public UserRole insert(UserRole userRole) throws DataAccessException {
        if (userRole == null) {
            throw new IllegalArgumentException("Can't insert a null data object into db.");
        }
        super.insert("UserRole.insert", userRole);
        return userRole;
    }

    /**
	 * 
	 * sql:UPDATE user_role SET delete_flag = 1 , update_time = CURRENT_TIMESTAMP(6) where delete_flag = 0 and id = ?
	 */
    public Long delete(Long id) throws DataAccessException {
        Map<String, Object> params = new HashMap<String, Object>(1);
        params.put("id", id);
        super.update("UserRole.delete", params);
        return id;
    }

    /**
	 * 
	 * sql:UPDATE user_role SET update_time= CURRENT_TIMESTAMP(6) , user_id = ? , role_id = ? , role_type = ? where delete_flag = 0 and id = ?
	 */
    public UserRole update(UserRole userRole) throws DataAccessException {
        if (userRole == null) {
            throw new IllegalArgumentException("Can't update by a null data object.");
        }
        super.update("UserRole.update", userRole);
        return userRole;
    }

    /**
	 * 
	 * sql:select a.id, a.user_id, a.role_id, a.role_type, a.create_time, a.update_time, a.delete_flag from user_role a where a.delete_flag = 0 and a.id = ?
	 */
    public UserRole getUserRoleById(Long id) throws DataAccessException {
        Map<String, Object> params = new HashMap<String, Object>(1);
        params.put("id", id);
        return (UserRole) super.selectOne("UserRole.getUserRoleById", params);
    }

    /**
	 * 
	 * sql:select a.id, a.user_id, a.role_id, a.role_type, a.create_time, a.update_time, a.delete_flag from user_role a where a.delete_flag = 0 and a.id=? and a.id in ( ? ) and a.user_id=? and a.user_id in ( ? ) and a.role_id=? and a.role_id in ( ? ) and a.role_type=? and a.role_type in ( ? ) and a.create_time >=? and a.create_time <? and a.update_time >=? and a.update_time <? and 0 = 1 order by a.update_time desc, a.create_time desc
	 */
    public PageList<UserRole> getPageList(UserRole userRole, int pageSize, int pageNum) throws DataAccessException {
        return super.pageQuery("UserRole.getPageList", userRole, pageNum, pageSize);
    }

    /**
	 * 
	 * sql:select a.id, a.user_id, a.role_id, a.role_type, a.create_time, a.update_time, a.delete_flag from user_role a where a.delete_flag = 0 and 1=0 and a.id in ( ? ) order by a.update_time desc, a.create_time desc
	 */
    public List<UserRole> getUserRolesByIds(java.util.List<Long> ids) throws DataAccessException {
        Map<String, Object> params = new HashMap<String, Object>(1);
        params.put("ids", ids);
        return super.selectList("UserRole.getUserRolesByIds", params);
    }

    /**
	 * 
	 * sql:UPDATE user_role SET delete_flag = 1 , update_time = CURRENT_TIMESTAMP(6) where delete_flag = 0 and 1=0 and id in ( ? )
	 */
    public java.util.List<Long> deleteByIds(java.util.List<Long> ids) throws DataAccessException {
        Map<String, Object> params = new HashMap<String, Object>(1);
        params.put("ids", ids);
        super.update("UserRole.deleteByIds", params);
        return ids;
    }
}
