/*
 * Do not remove this unless you get business authorization.
 * Copyright (c) 2016 - 2018 All Rights Reserved.
 * Powered By [stategen.dalgen]
 */
package com.mycompany.biz.service;

import java.util.List;

import org.stategen.framework.lite.PageList;
import org.stategen.framework.util.AssignService;

import com.mycompany.biz.domain.City;

/**
 * CityService
 * <pre>
 * database table: city
 * database table comments: City
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 *
 * 新生成的类中的方法，只有在不同名的情况下才会被追加到该类下，
 * 因此该类可以修改任何部分
 * </pre>
 */
public interface CityService extends AssignService<City, String>, CityServiceTrade {

    //<#--
    /**
     * 
     * @see com.mycompany.biz.dao.CityDao#insert
     */
    public City insert(City city);

    /**
     * 
     * @see com.mycompany.biz.dao.CityDao#delete
     */
    public String delete(String cityId);

    /**
     * 
     * @see com.mycompany.biz.dao.CityDao#update
     */
    public City update(City city);

    /**
     * 
     * @see com.mycompany.biz.dao.CityDao#getCityByCityId
     */
    public City getCityByCityId(String cityId);

    /**
     * 
     * @see com.mycompany.biz.dao.CityDao#getCityPageList
     */
    public PageList<City> getCityPageList(City city, int pageSize, int pageNum);

    /**
     * 
     * @see com.mycompany.biz.dao.CityDao#getCitysByCityIds
     */
    public List<City> getCitysByCityIds(java.util.List<String> cityIds);

    /**
     * 
     * @see com.mycompany.biz.dao.CityDao#deleteByCityIds
     */
    public java.util.List<String> deleteByCityIds(java.util.List<String> cityIds);

    /*** 保存city,有id时更新，没有id时插入,并带回新的id，返回 city
     * @see com.mycompany.biz.dao.CityDao#insert
     */
    public City saveCity(City city);

    /** 批量保存citys,有id时更新，没有id时插入,并带回新的id，返回 citys
     * @see com.mycompany.biz.dao.CityDao#insert
     */
    public List<City> saveCitys(List<City> citys);

    /**
     * 
     * @see com.mycompany.biz.dao.CityDao#getCityOptions
     */
    public List<City> getCityOptions(String provinceId);
    //-->
    //
}
