/*
 * Do not remove this unless you get business authorization.
 * Copyright (c) 2016 - 2018 All Rights Reserved.
 * Powered By [stategen.dalgen]
 */
package com.mycompany.biz.service;

import java.util.List;

import org.stategen.framework.lite.PageList;
import org.stategen.framework.util.AssignService;
import org.stategen.framework.util.BaseService;

import com.mycompany.biz.domain.HomeAdvertise;

/**
 * HomeAdvertiseService
 * <pre>
 * database table: home_advertise
 * database table comments: HomeAdvertise
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 *
 * 新生成的类中的方法，只有在不同名的情况下才会被追加到该类下，
 * 因此该类可以修改任何部分
 * </pre>
 */
public interface HomeAdvertiseService extends HomeAdvertiseServiceTrade, AssignService<HomeAdvertise, String>, BaseService<HomeAdvertise> {

    /**
     * 
     * @see com.mycompany.biz.dao.HomeAdvertiseDao#insert
     */
    public HomeAdvertise insert(HomeAdvertise homeAdvertise);

    /**
     * 
     * @see com.mycompany.biz.dao.HomeAdvertiseDao#delete
     */
    public String delete(String homeAdvId);

    /**
     * 
     * @see com.mycompany.biz.dao.HomeAdvertiseDao#update
     */
    public HomeAdvertise update(HomeAdvertise homeAdvertise);

    /**
     * 
     * @see com.mycompany.biz.dao.HomeAdvertiseDao#getHomeAdvertiseByHomeAdvId
     */
    public HomeAdvertise getHomeAdvertiseByHomeAdvId(String homeAdvId);

    /**
     * 
     * @see com.mycompany.biz.dao.HomeAdvertiseDao#getHomeAdvertisesByHomeAdvIds
     */
    public List<HomeAdvertise> getHomeAdvertisesByHomeAdvIds(java.util.List<String> homeAdvIds);

    /**
     * 
     * @see com.mycompany.biz.dao.HomeAdvertiseDao#deleteByHomeAdvIds
     */
    public java.util.List<String> deleteByHomeAdvIds(java.util.List<String> homeAdvIds);

    /*** 保存homeAdvertise,有id时更新，没有id时插入,并带回新的id，返回 homeAdvertise
     * @see com.mycompany.biz.dao.HomeAdvertiseDao#insert
     */
    public HomeAdvertise saveHomeAdvertise(HomeAdvertise homeAdvertise);

    /** 批量保存homeAdvertises,有id时更新，没有id时插入,并带回新的id，返回 homeAdvertises
     * @see com.mycompany.biz.dao.HomeAdvertiseDao#insert
     */
    public List<HomeAdvertise> saveHomeAdvertises(List<HomeAdvertise> homeAdvertises);

    /**
     * 
     * @see com.mycompany.biz.dao.HomeAdvertiseDao#getPageList
     */
    public PageList<HomeAdvertise> getPageList(HomeAdvertise homeAdvertise, int pageSize, int pageNum);
}
