/*
 * Do not remove this unless you get business authorization.
 * Copyright (c) 2016 - 2018 All Rights Reserved.
 * Powered By [stategen.dalgen]
 */
package com.mycompany.biz.service;

import java.util.List;

import org.stategen.framework.lite.PageList;
import org.stategen.framework.util.AssignService;
import org.stategen.framework.util.BaseService;

import com.mycompany.biz.domain.Shop;

/**
 * ShopService
 * <pre>
 * database table: shop
 * database table comments: Shop
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 *
 * 新生成的类中的方法，只有在不同名的情况下才会被追加到该类下，
 * 因此该类可以修改任何部分
 * </pre>
 */
public interface ShopService extends ShopServiceTrade, AssignService<Shop, String>, BaseService<Shop> {

    /**
     * 
     * @see com.mycompany.biz.dao.ShopDao#insert
     */
    public Shop insert(Shop shop);

    /**
     * 
     * @see com.mycompany.biz.dao.ShopDao#delete
     */
    public String delete(String shopId);

    /**
     * 
     * @see com.mycompany.biz.dao.ShopDao#update
     */
    public Shop update(Shop shop);

    /**
     * 
     * @see com.mycompany.biz.dao.ShopDao#getShopByShopId
     */
    public Shop getShopByShopId(String shopId);

    /**
     * 
     * @see com.mycompany.biz.dao.ShopDao#getShopsByShopIds
     */
    public List<Shop> getShopsByShopIds(java.util.List<String> shopIds);

    /**
     * 
     * @see com.mycompany.biz.dao.ShopDao#deleteByShopIds
     */
    public java.util.List<String> deleteByShopIds(java.util.List<String> shopIds);

    /*** 保存shop,有id时更新，没有id时插入,并带回新的id，返回 shop
     * @see com.mycompany.biz.dao.ShopDao#insert
     */
    public Shop saveShop(Shop shop);

    /** 批量保存shops,有id时更新，没有id时插入,并带回新的id，返回 shops
     * @see com.mycompany.biz.dao.ShopDao#insert
     */
    public List<Shop> saveShops(List<Shop> shops);

    /**
     * 
     * @see com.mycompany.biz.dao.ShopDao#getPageList
     */
    public PageList<Shop> getPageList(Shop shop, int pageSize, int pageNum);
}
