/*
 * Do not remove this unless you get business authorization.
 * Copyright (c) 2016 - 2018 All Rights Reserved.
 * Powered By [stategen.dalgen]
 */
package com.mycompany.biz.service;

import java.util.List;

import org.stategen.framework.lite.PageList;
import org.stategen.framework.util.AssignSerice;

import com.mycompany.biz.domain.UserColor;

/**
 * UserColorService
 * <pre>
 * database table: user_color
 * database table comments: UserColor
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 *
 * 新生成的类中的方法，只有在不同名的情况下才会被追加到该类下，
 * 因此该类可以修改任何部分
 * </pre>
 */
public interface UserColorService extends AssignSerice<UserColor, Integer>, UserColorServiceTrade {

    /**
     * 
     * @see com.mycompany.biz.dao.UserColorDao#insert
     */
    public UserColor insert(UserColor userColor);

    /**
     * 
     * @see com.mycompany.biz.dao.UserColorDao#delete
     */
    public Integer delete(Integer id);

    /**
     * 
     * @see com.mycompany.biz.dao.UserColorDao#update
     */
    public UserColor update(UserColor userColor);

    /**
     * 
     * @see com.mycompany.biz.dao.UserColorDao#getUserColorById
     */
    public UserColor getUserColorById(Integer id);

    /**
     * 
     * @see com.mycompany.biz.dao.UserColorDao#getUserColorPageList
     */
    public PageList<UserColor> getUserColorPageList(UserColor userColor, int pageSize, int pageNum);

    /**
     * 
     * @see com.mycompany.biz.dao.UserColorDao#getUserColorsByIds
     */
    public List<UserColor> getUserColorsByIds(java.util.List<Integer> ids);

    /**
     * 
     * @see com.mycompany.biz.dao.UserColorDao#deleteByIds
     */
    public java.util.List<Integer> deleteByIds(java.util.List<Integer> ids);

    /*** 保存userColor,有id时更新，没有id时插入,并带回新的id，返回 userColor
     * @see com.mycompany.biz.dao.UserColorDao#insert
     */
    public UserColor saveUserColor(UserColor userColor);

    /** 批量保存userColors,有id时更新，没有id时插入,并带回新的id，返回 userColors
     * @see com.mycompany.biz.dao.UserColorDao#insert
     */
    public List<UserColor> saveUserColors(List<UserColor> userColors);
}
