/*
 * Do not remove this unless you get business authorization.
 * Copyright (c) 2016 - 2018 All Rights Reserved.
 * Powered By [stategen.dalgen]
 */
package com.mycompany.biz.domain;

import java.text.SimpleDateFormat;
import java.util.List;

import javax.persistence.Id;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Max;

import com.alibaba.fastjson.annotation.JSONField;
import io.swagger.annotations.ApiModelProperty;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Floor
 * <pre>
 * database table: demo_floor
 * database table comments: Floor
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 *
 * 该类仅不可以修改dalgen生成的属生(field)类型 ,方法(Method)返回值类型和参数类型
 * 不建议使@Data,其hashCode有问题
 * </pre>
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Floor implements java.io.Serializable {

    List<FloorGoods> floorGoodss;

    AdvertisePicture advertisePicture;

    private static final long serialVersionUID = -5216457518046898601L;

    /***floorId   db_column: floor_id VARCHAR */
    @ApiModelProperty("floorId")
    @Id
    @Max(64)
    private String floorId;

    /***advertiseId   db_column: advertise_id BIGINT */
    @ApiModelProperty("advertiseId")
    @Max(64)
    private Long advertiseId;

    /***orderNo   db_column: order_no INTEGER */
    @ApiModelProperty("orderNo")
    private Integer orderNo;

    /***floorName   db_column: floor_name VARCHAR */
    @ApiModelProperty("floorName")
    @Max(32)
    private String floorName;

    /***创建时间   db_column: create_time TIMESTAMP */
    @ApiModelProperty(value = "创建时间", hidden = true)
    @Temporal(TemporalType.TIMESTAMP)
    private java.util.Date createTime;

    /***更新时间   db_column: update_time TIMESTAMP */
    @ApiModelProperty(value = "更新时间", hidden = true)
    @Temporal(TemporalType.TIMESTAMP)
    private java.util.Date updateTime;

    /***是否删除(0:正常，1删除)   db_column: delete_flag INTEGER */
    @ApiModelProperty(value = "是否删除(0:正常，1删除)", hidden = true)
    private Integer deleteFlag;

    /*----------------getter & setter ignore by lombok -------------------*/
    public String toString() {
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd H:m:ss.SSS");
        StringBuilder sb = new StringBuilder(1024);
        sb.append('{');
        sb.append("floorIds=").append(floorIds).append('\n');
        sb.append("advertiseIds=").append(advertiseIds).append('\n');
        sb.append("orderNoMin=").append(orderNoMin).append('\n');
        sb.append("orderNoMax=").append(orderNoMax).append('\n');
        sb.append("floorNameLike=").append(floorNameLike).append('\n');
        sb.append("createTimeMin=").append(createTimeMin != null ? df.format(createTimeMin) : null).append('\n');
        sb.append("createTimeMax=").append(createTimeMax != null ? df.format(createTimeMax) : null).append('\n');
        sb.append("updateTimeMin=").append(updateTimeMin != null ? df.format(updateTimeMin) : null).append('\n');
        sb.append("updateTimeMax=").append(updateTimeMax != null ? df.format(updateTimeMax) : null).append('\n');
        sb.append("floorId=").append(floorId).append('\n');
        sb.append("advertiseId=").append(advertiseId).append('\n');
        sb.append("orderNo=").append(orderNo).append('\n');
        sb.append("floorName=").append(floorName).append('\n');
        sb.append("createTime=").append(createTime != null ? df.format(createTime) : null).append('\n');
        sb.append("updateTime=").append(updateTime != null ? df.format(updateTime) : null).append('\n');
        sb.append("deleteFlag=").append(deleteFlag);
        sb.append('}');
        return sb.toString();
    }

    /*** floorIds in getPageList */
    @ApiModelProperty("floorId s")
    @JSONField(serialize = false)
    private java.util.List<String> floorIds;

    /*** advertiseIds in getPageList */
    @ApiModelProperty("advertiseId s")
    @JSONField(serialize = false)
    private java.util.List<Long> advertiseIds;

    /*** orderNoMin in getPageList */
    @ApiModelProperty("orderNoMin")
    @JSONField(serialize = false)
    private Integer orderNoMin;

    /*** orderNoMax in getPageList */
    @ApiModelProperty("orderNoMax")
    @JSONField(serialize = false)
    private Integer orderNoMax;

    /*** floorNameLike in getPageList */
    @ApiModelProperty("floorNameLike")
    @JSONField(serialize = false)
    private String floorNameLike;

    /*** 创建时间Min in getPageList */
    @ApiModelProperty("创建时间Min")
    @Temporal(TemporalType.TIMESTAMP)
    @JSONField(serialize = false)
    private java.util.Date createTimeMin;

    /*** 创建时间Max in getPageList */
    @ApiModelProperty("创建时间Max")
    @Temporal(TemporalType.TIMESTAMP)
    @JSONField(serialize = false)
    private java.util.Date createTimeMax;

    /*** 更新时间Min in getPageList */
    @ApiModelProperty("更新时间Min")
    @Temporal(TemporalType.TIMESTAMP)
    @JSONField(serialize = false)
    private java.util.Date updateTimeMin;

    /*** 更新时间Max in getPageList */
    @ApiModelProperty("更新时间Max")
    @Temporal(TemporalType.TIMESTAMP)
    @JSONField(serialize = false)
    private java.util.Date updateTimeMax;
}
