/*
 * Do not remove this unless you get business authorization.
 * Copyright (c) 2016 - 2018 All Rights Reserved.
 * Powered By [stategen.dalgen]
 */
package com.mycompany.biz.domain;

import java.text.SimpleDateFormat;

import javax.persistence.Id;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Max;

import org.stategen.framework.annotation.OptionConvertor;
import org.stategen.framework.lite.IOption;

import com.alibaba.fastjson.annotation.JSONField;
import com.mycompany.biz.enums.RegionType;
import io.swagger.annotations.ApiModelProperty;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Region
 * @author StateGen.org
 * <pre>
 * database table: demo_region
 * database table comments: 全球地区库，采集自腾讯QQ国内+国际版.ADD.JENA.20141221
 * This file is generated by <tt>dalgenx</tt>, a DAL (Data Access Layer)
 *
 * 该类仅不可以修改dalgenx生成的属生(field)类型 ,方法(Method)返回值类型和参数类型
 * 该类可自由继承、实现接口，自定义字段或方法，在下次生成时均不会丢失，可有效减少DTO的使用.
 * 同时，支持自定义修改字段大小写，一旦修改后，请再执行 gen.sh dal demo_region -e
 * 不建议使@Data,其hashCode有问题
 * 如果表修改后 ，请执行 gen.sh table demo_region -e ,再执行 gen.sh dal demo_region -e
 * </pre>
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@OptionConvertor(parentId = "parentRegionId", label = "name")
public class Region implements java.io.Serializable, IOption {

    private Boolean isLeaf;

    /***不使用或自定义字段在下次生成后，会移到serialVersionUID的上面
     ** 额外查询字段，自定义方法会自动移到toString()的下面
     ** 如果字段注释中包括 ‘-inherited’, 将不生成，字段可以从父类中继承
     ** ps: 该方案既享受生成器的便利，pojo可以同时作为po dto vo使用，而不用担心字段丢失问题,
     **     同时解决领域模型(DDD)开发中，失血模式下的失忆问题
     */
    private static final long serialVersionUID = -5216457518046898601L;

    /***主键   db_column: region_id BIGINT */
    @ApiModelProperty("主键")
    @Id
    private Long regionId;

    /***父ID   db_column: parent_region_id BIGINT */
    @ApiModelProperty("父ID")
    private Long parentRegionId;

    /***路径   db_column: path VARCHAR */
    @ApiModelProperty("路径")
    @Max(255)
    private String path;

    /***层级   db_column: level INTEGER */
    @ApiModelProperty("层级")
    private Integer level;

    /***regionType   db_column: region_type VARCHAR */
    @ApiModelProperty("regionType")
    private RegionType regionType;

    /***中文名称   db_column: name VARCHAR */
    @ApiModelProperty("中文名称")
    @Max(255)
    private String name;

    /***英文名称   db_column: name_en VARCHAR */
    @ApiModelProperty("英文名称")
    @Max(255)
    private String nameEn;

    /***中文拼音   db_column: name_pinyin VARCHAR */
    @ApiModelProperty("中文拼音")
    @Max(255)
    private String namePinyin;

    /***代码   db_column: code VARCHAR */
    @ApiModelProperty("代码")
    @Max(50)
    private String code;

    /***更新时间   db_column: update_time TIMESTAMP */
    @ApiModelProperty(value = "更新时间", hidden = true)
    @Temporal(TemporalType.TIMESTAMP)
    private java.util.Date updateTime;

    /***创建时间   db_column: create_time TIMESTAMP */
    @ApiModelProperty(value = "创建时间", hidden = true)
    @Temporal(TemporalType.TIMESTAMP)
    private java.util.Date createTime;

    /***是否删除 (0:正常，1删除)   db_column: delete_flag BIT */
    @ApiModelProperty(value = "是否删除 (0:正常，1删除)", hidden = true)
    private Boolean deleteFlag;

    /*----------------getter & setter ignore by lombok -------------------*/
    public String toString() {
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd H:m:ss.SSS");
        StringBuilder sb = new StringBuilder(1024);
        sb.append('{');
        sb.append("regionIds").append('=').append(regionIds).append('\n');
        sb.append("parentRegionIds").append('=').append(parentRegionIds).append('\n');
        sb.append("pathLike").append('=').append(pathLike).append('\n');
        sb.append("levelMin").append('=').append(levelMin).append('\n');
        sb.append("levelMax").append('=').append(levelMax).append('\n');
        sb.append("regionTypes").append('=').append(regionTypes).append('\n');
        sb.append("nameLike").append('=').append(nameLike).append('\n');
        sb.append("nameEnLike").append('=').append(nameEnLike).append('\n');
        sb.append("namePinyinLike").append('=').append(namePinyinLike).append('\n');
        sb.append("codeLike").append('=').append(codeLike).append('\n');
        sb.append("updateTimeMin").append('=').append(updateTimeMin != null ? df.format(updateTimeMin) : null).append('\n');
        sb.append("updateTimeMax").append('=').append(updateTimeMax != null ? df.format(updateTimeMax) : null).append('\n');
        sb.append("createTimeMin").append('=').append(createTimeMin != null ? df.format(createTimeMin) : null).append('\n');
        sb.append("createTimeMax").append('=').append(createTimeMax != null ? df.format(createTimeMax) : null).append('\n');
        sb.append("regionId").append('=').append(getRegionId()).append('\n');
        sb.append("parentRegionId").append('=').append(getParentRegionId()).append('\n');
        sb.append("path").append('=').append(getPath()).append('\n');
        sb.append("level").append('=').append(getLevel()).append('\n');
        sb.append("regionType").append('=').append(getRegionType()).append('\n');
        sb.append("name").append('=').append(getName()).append('\n');
        sb.append("nameEn").append('=').append(getNameEn()).append('\n');
        sb.append("namePinyin").append('=').append(getNamePinyin()).append('\n');
        sb.append("code").append('=').append(getCode()).append('\n');
        sb.append("updateTime").append('=').append(getUpdateTime() != null ? df.format(getUpdateTime()) : null).append('\n');
        sb.append("createTime").append('=').append(getCreateTime() != null ? df.format(getCreateTime()) : null).append('\n');
        sb.append("deleteFlag").append('=').append(getDeleteFlag());
        sb.append('}');
        return sb.toString();
    }

    /***查询字段下次生成时会自动移到toString()方法下面*/
    /*** 主键s in getPageList */
    @ApiModelProperty("主键 s")
    @JSONField(serialize = false)
    private java.util.List<Long> regionIds;

    /*** 父IDs in getPageList */
    @ApiModelProperty("父ID s")
    @JSONField(serialize = false)
    private java.util.List<Long> parentRegionIds;

    /*** 路径Like in getPageList */
    @ApiModelProperty("路径Like")
    @JSONField(serialize = false)
    private String pathLike;

    /*** 层级Min in getPageList */
    @ApiModelProperty("层级Min")
    @JSONField(serialize = false)
    private Integer levelMin;

    /*** 层级Max in getPageList */
    @ApiModelProperty("层级Max")
    @JSONField(serialize = false)
    private Integer levelMax;

    /*** regionTypes in getPageList */
    @ApiModelProperty("regionType s")
    @JSONField(serialize = false)
    private java.util.List<com.mycompany.biz.enums.RegionType> regionTypes;

    /*** 中文名称Like in getPageList */
    @ApiModelProperty("中文名称Like")
    @JSONField(serialize = false)
    private String nameLike;

    /*** 英文名称Like in getPageList */
    @ApiModelProperty("英文名称Like")
    @JSONField(serialize = false)
    private String nameEnLike;

    /*** 中文拼音Like in getPageList */
    @ApiModelProperty("中文拼音Like")
    @JSONField(serialize = false)
    private String namePinyinLike;

    /*** 代码Like in getPageList */
    @ApiModelProperty("代码Like")
    @JSONField(serialize = false)
    private String codeLike;

    /*** 更新时间Min in getPageList */
    @ApiModelProperty("更新时间Min")
    @Temporal(TemporalType.TIMESTAMP)
    @JSONField(serialize = false)
    private java.util.Date updateTimeMin;

    /*** 更新时间Max in getPageList */
    @ApiModelProperty("更新时间Max")
    @Temporal(TemporalType.TIMESTAMP)
    @JSONField(serialize = false)
    private java.util.Date updateTimeMax;

    /*** 创建时间Min in getPageList */
    @ApiModelProperty("创建时间Min")
    @Temporal(TemporalType.TIMESTAMP)
    @JSONField(serialize = false)
    private java.util.Date createTimeMin;

    /*** 创建时间Max in getPageList */
    @ApiModelProperty("创建时间Max")
    @Temporal(TemporalType.TIMESTAMP)
    @JSONField(serialize = false)
    private java.util.Date createTimeMax;

    @Override
    public String getTitle() {
        return getName();
    }

    @Override
    public String getValue() {
        if (regionId == null) {
            return null;
        }
        return regionId.toString();
    }
}
