/*
 * Do not remove this unless you get business authorization.
 * Copyright (c) 2016 - 2018 All Rights Reserved.
 * Powered By [stategen.dalgen]
 */
package com.mycompany.biz.domain;

import java.text.SimpleDateFormat;

import javax.persistence.Id;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Max;
import javax.validation.constraints.NotNull;
import io.swagger.annotations.ApiModelProperty;

import lombok.Getter;
import lombok.Setter;

/**
 * TopicAuthor
 * <pre>
 * database table: topic_author
 * database table comments: TopicAuthor
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 *
 * 该类仅不可以修改dalgen生成的属生(field)类型 ,方法(Method)返回值类型和参数类型
 * 不建议使@Data,其hashCode有问题
 * </pre>
 */
@Getter
@Setter
public class TopicAuthor implements java.io.Serializable {

    private static final long serialVersionUID = -5216457518046898601L;

    /***authorId   db_column: author_id VARCHAR */
    @ApiModelProperty("authorId")
    @Id
    @Max(64)
    private String authorId;

    /***loginname   db_column: loginname VARCHAR */
    @ApiModelProperty("loginname")
    @NotNull
    @Max(32)
    private String loginname;

    /***avatarUrl   db_column: avatar_url VARCHAR */
    @ApiModelProperty("avatarUrl")
    @Max(255)
    private String avatarUrl;

    /***创建时间   db_column: create_time TIMESTAMP */
    @ApiModelProperty(value = "创建时间", hidden = true)
    @Temporal(TemporalType.TIMESTAMP)
    private java.util.Date createTime;

    /***更新时间   db_column: update_time TIMESTAMP */
    @ApiModelProperty(value = "更新时间", hidden = true)
    @Temporal(TemporalType.TIMESTAMP)
    private java.util.Date updateTime;

    /***是否删除(0:正常，1删除)   db_column: delete_flag INTEGER */
    @ApiModelProperty(value = "是否删除(0:正常，1删除)", hidden = true)
    private Integer deleteFlag;

    /*----------------getter & setter ignore by lombok -------------------*/
    public String toString() {
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd H:m:ss.SSS");
        StringBuffer sb = new StringBuffer(1024);
        sb.append('{');
        sb.append("authorIds=").append(authorIds).append('\n');
        sb.append("loginnameLike=").append(loginnameLike).append('\n');
        sb.append("avatarUrlLike=").append(avatarUrlLike).append('\n');
        sb.append("createTimeMin=").append(createTimeMin != null ? df.format(createTimeMin) : null).append('\n');
        sb.append("createTimeMax=").append(createTimeMax != null ? df.format(createTimeMax) : null).append('\n');
        sb.append("updateTimeMin=").append(updateTimeMin != null ? df.format(updateTimeMin) : null).append('\n');
        sb.append("updateTimeMax=").append(updateTimeMax != null ? df.format(updateTimeMax) : null).append('\n');
        sb.append("authorId=").append(authorId).append('\n');
        sb.append("loginname=").append(loginname).append('\n');
        sb.append("avatarUrl=").append(avatarUrl).append('\n');
        sb.append("createTime=").append(createTime != null ? df.format(createTime) : null).append('\n');
        sb.append("updateTime=").append(updateTime != null ? df.format(updateTime) : null).append('\n');
        sb.append("deleteFlag=").append(deleteFlag);
        sb.append('}');
        return sb.toString();
    }

    /*** authorIds in getTopicAuthorPageListByDefaultQuery */
    @ApiModelProperty("authorIds")
    private transient java.util.List<String> authorIds;

    /*** loginnameLike in getTopicAuthorPageListByDefaultQuery */
    @ApiModelProperty("loginnameLike")
    private transient String loginnameLike;

    /*** avatarUrlLike in getTopicAuthorPageListByDefaultQuery */
    @ApiModelProperty("avatarUrlLike")
    private transient String avatarUrlLike;

    /*** 创建时间Min in getTopicAuthorPageListByDefaultQuery */
    @ApiModelProperty("创建时间Min")
    @Temporal(TemporalType.TIMESTAMP)
    private transient java.util.Date createTimeMin;

    /*** 创建时间Max in getTopicAuthorPageListByDefaultQuery */
    @ApiModelProperty("创建时间Max")
    @Temporal(TemporalType.TIMESTAMP)
    private transient java.util.Date createTimeMax;

    /*** 更新时间Min in getTopicAuthorPageListByDefaultQuery */
    @ApiModelProperty("更新时间Min")
    @Temporal(TemporalType.TIMESTAMP)
    private transient java.util.Date updateTimeMin;

    /*** 更新时间Max in getTopicAuthorPageListByDefaultQuery */
    @ApiModelProperty("更新时间Max")
    @Temporal(TemporalType.TIMESTAMP)
    private transient java.util.Date updateTimeMax;

    public String getAvatar_url() {
        return avatarUrl;
    }

    public void SetAvatar_url(String id) {
        this.avatarUrl = id;
    }

    public String getId() {
        return authorId;
    }

    public void setId(String id) {
        this.authorId = id;
    }
}
