#　　–file:./config/ > 　–file:./ > –classpath:/config/ >　–classpath:/
spring:
  cloud:
    stream:
#      function:
#        definition: supplier;receiveAuth   
      #上面的  definition 由下面的 definition-method-map根据 map的key动态提供，一个系统有多个订阅方，  
      definition-method-map:
        supplier: 1
        receiveAuth: 1
      bindings:
        receiveAuth-in-0:
          destination: receiveAuth-dest
          group: receiveAuth-group
          
       