/*
 * Do not remove this unless you get business authorization.
 * Copyright (c) 2016 - 2018 All Rights Reserved.
 * Powered By [stategen.dalgen]
 */
package com.mycompany.biz.dao;

import java.util.List;

import com.mycompany.biz.domain.User;
import org.springframework.dao.DataAccessException;
import org.stategen.framework.lite.PageList;
import org.stategen.framework.lite.IdGenerateService;

/**
 * UserDao
 * @author StageGen.org
 * <pre>
 * database table: user
 * database table comments: User
 * This file is generated by <tt>dalgenx</tt>, a DAL (Data Access Layer)
 *
 * 该类仅可以修改引用
 * </pre>
 */
public interface UserDao {

	/**
    <pre>
    &#64;ApiParam() &#64;RequestParam(required = false) String userId,
    &#64;ApiParam() &#64;RequestParam(required = false) String username,
    &#64;ApiParam() &#64;RequestParam(required = false) String password,
    &#64;ApiParam() &#64;RequestParam(required = false) RoleType roleType,
    &#64;ApiParam() &#64;RequestParam(required = false) String name,
    &#64;ApiParam() &#64;RequestParam(required = false) String nickName,
    &#64;ApiParam() &#64;RequestParam(required = false) String interCode,
    &#64;ApiParam() &#64;RequestParam(required = false) String mobile,
    &#64;ApiParam() &#64;RequestParam(required = false) Integer age,
    &#64;ApiParam() &#64;RequestParam(required = false) String address,
    &#64;ApiParam() &#64;RequestParam(required = false) String avatarImgId,
    &#64;ApiParam() &#64;RequestParam(required = false) String email,
    &#64;ApiParam() &#64;RequestParam(required = false) Date valiDatetime,
    &#64;ApiParam() &#64;RequestParam(required = false) Date birthdayDate,
    &#64;ApiParam() &#64;RequestParam(required = false) Date workTime,
    &#64;ApiParam() &#64;RequestParam(required = false) String provinceId,
    &#64;ApiParam() &#64;RequestParam(required = false) String cityId,
    &#64;ApiParam() &#64;RequestParam(required = false) StatusEnum status,
    &#64;ApiParam() &#64;RequestParam(required = false) Long grade,
    &#64;ApiParam() &#64;RequestParam(required = false) Boolean sex,
    &#64;ApiParam() &#64;RequestParam(required = false) Long postAddressId,
    &#64;ApiParam() &#64;RequestParam(required = false) String remark
    ,&#64;ApiParam(hidden = true) User user
    
    </pre>
	 * 
	 * sql:insert into user ( create_time , update_time , delete_flag , user_id , username , password , role_type , name , nickName , inter_code , mobile , age , address , avatar_img_id , email , vali_datetime , birthday_date , work_time , province_id , city_id , status , grade , sex , post_address_id , remark ) VALUES (CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6),0,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
	 */
	public User insert(User user, IdGenerateService<String> idGenerateService) throws DataAccessException;
	
	/**
    <pre>
    &#64;ApiParam("用户ID") &#64;RequestParam(required = false) String userId    
    </pre>
	 * 
	 * sql:UPDATE user a SET a.delete_flag = 1 , a.update_time = CURRENT_TIMESTAMP(6) where a.delete_flag = 0 and a.user_id = ?
	 */
	public String delete(String userId) throws DataAccessException;
	
	/**
    <pre>
    &#64;ApiParam("用户名") &#64;RequestParam(required = false) String username    
    </pre>
	 * 
	 * sql:UPDATE user a SET a.delete_flag = 1 , a.update_time = CURRENT_TIMESTAMP(6) where a.delete_flag = 0 and a.username = ?
	 */
	public Long deleteByUsername(String username) throws DataAccessException;
	
	/**
    <pre>
    &#64;ApiParam("邮箱") &#64;RequestParam(required = false) String email    
    </pre>
	 * 
	 * sql:UPDATE user a SET a.delete_flag = 1 , a.update_time = CURRENT_TIMESTAMP(6) where a.delete_flag = 0 and a.email = ?
	 */
	public Long deleteByEmail(String email) throws DataAccessException;
	
	/**
    <pre>
    &#64;ApiParam() &#64;RequestParam(required = false) String username,
    &#64;ApiParam() &#64;RequestParam(required = false) String password,
    &#64;ApiParam() &#64;RequestParam(required = false) RoleType roleType,
    &#64;ApiParam() &#64;RequestParam(required = false) String name,
    &#64;ApiParam() &#64;RequestParam(required = false) String nickName,
    &#64;ApiParam() &#64;RequestParam(required = false) String interCode,
    &#64;ApiParam() &#64;RequestParam(required = false) String mobile,
    &#64;ApiParam() &#64;RequestParam(required = false) Integer age,
    &#64;ApiParam() &#64;RequestParam(required = false) String address,
    &#64;ApiParam() &#64;RequestParam(required = false) String avatarImgId,
    &#64;ApiParam() &#64;RequestParam(required = false) String email,
    &#64;ApiParam() &#64;RequestParam(required = false) Date valiDatetime,
    &#64;ApiParam() &#64;RequestParam(required = false) Date birthdayDate,
    &#64;ApiParam() &#64;RequestParam(required = false) Date workTime,
    &#64;ApiParam() &#64;RequestParam(required = false) String provinceId,
    &#64;ApiParam() &#64;RequestParam(required = false) String cityId,
    &#64;ApiParam() &#64;RequestParam(required = false) StatusEnum status,
    &#64;ApiParam() &#64;RequestParam(required = false) Long grade,
    &#64;ApiParam() &#64;RequestParam(required = false) Boolean sex,
    &#64;ApiParam() &#64;RequestParam(required = false) Long postAddressId,
    &#64;ApiParam() &#64;RequestParam(required = false) String remark,
    &#64;ApiParam() &#64;RequestParam(required = false) String userId
    ,&#64;ApiParam(hidden = true) User user
    
    </pre>
	 * 
	 * sql:UPDATE user a SET a.update_time= CURRENT_TIMESTAMP(6) , a.username = ? , a.password = ? , a.role_type = ? , a.name = ? , a.nickName = ? , a.inter_code = ? , a.mobile = ? , a.age = ? , a.address = ? , a.avatar_img_id = ? , a.email = ? , a.vali_datetime = ? , a.birthday_date = ? , a.work_time = ? , a.province_id = ? , a.city_id = ? , a.status = ? , a.grade = ? , a.sex = ? , a.post_address_id = ? , a.remark = ? where a.delete_flag = 0 and a.user_id = ?
	 */
	public User update(User user) throws DataAccessException;
	
	/**
    <pre>
    &#64;ApiParam("用户ID") &#64;RequestParam(required = false) String userId    
    </pre>
	 * 
	 * sql:select a.user_id, a.username, a.password, a.role_type, a.name, a.nickName, a.inter_code, a.mobile, a.age, a.address, a.avatar_img_id, a.email, a.vali_datetime, a.birthday_date, a.work_time, a.province_id, a.city_id, a.status, a.grade, a.sex, a.post_address_id, a.remark, a.update_time, a.create_time, a.delete_flag from user a where a.delete_flag = 0 and a.user_id = ?
	 */
	public User getUserByUserId(String userId) throws DataAccessException;
	
	/**
    <pre>
    &#64;ApiParam("用户名") &#64;RequestParam(required = false) String username    
    </pre>
	 * 
	 * sql:select a.user_id, a.username, a.password, a.role_type, a.name, a.nickName, a.inter_code, a.mobile, a.age, a.address, a.avatar_img_id, a.email, a.vali_datetime, a.birthday_date, a.work_time, a.province_id, a.city_id, a.status, a.grade, a.sex, a.post_address_id, a.remark, a.update_time, a.create_time, a.delete_flag from user a where a.delete_flag = 0 and a.username = ?
	 */
	public User getUserByUsername(String username) throws DataAccessException;
	
	/**
    <pre>
    &#64;ApiParam("邮箱") &#64;RequestParam(required = false) String email    
    </pre>
	 * 
	 * sql:select a.user_id, a.username, a.password, a.role_type, a.name, a.nickName, a.inter_code, a.mobile, a.age, a.address, a.avatar_img_id, a.email, a.vali_datetime, a.birthday_date, a.work_time, a.province_id, a.city_id, a.status, a.grade, a.sex, a.post_address_id, a.remark, a.update_time, a.create_time, a.delete_flag from user a where a.delete_flag = 0 and a.email = ?
	 */
	public User getUserByEmail(String email) throws DataAccessException;
	
	/**
    <pre>
    &#64;ApiParam() &#64;RequestParam(required = false) String userId,
    &#64;ApiParam() &#64;RequestParam(required = false, name="userIds") ArrayList&lt;String&gt; userIds,
    &#64;ApiParam() &#64;RequestParam(required = false) String username,
    &#64;ApiParam() &#64;RequestParam(required = false) String usernameLike,
    &#64;ApiParam() &#64;RequestParam(required = false) String password,
    &#64;ApiParam() &#64;RequestParam(required = false) String passwordLike,
    &#64;ApiParam() &#64;RequestParam(required = false) RoleType roleType,
    &#64;ApiParam() &#64;RequestParam(required = false, name="roleTypes") ArrayList&lt;RoleType&gt; roleTypes,
    &#64;ApiParam() &#64;RequestParam(required = false) String name,
    &#64;ApiParam() &#64;RequestParam(required = false) String nameLike,
    &#64;ApiParam() &#64;RequestParam(required = false) String nickName,
    &#64;ApiParam() &#64;RequestParam(required = false) String nickNameLike,
    &#64;ApiParam() &#64;RequestParam(required = false) String interCode,
    &#64;ApiParam() &#64;RequestParam(required = false) String interCodeLike,
    &#64;ApiParam() &#64;RequestParam(required = false) String mobile,
    &#64;ApiParam() &#64;RequestParam(required = false) String mobileLike,
    &#64;ApiParam() &#64;RequestParam(required = false) Integer age,
    &#64;ApiParam() &#64;RequestParam(required = false) Integer ageMin,
    &#64;ApiParam() &#64;RequestParam(required = false) Integer ageMax,
    &#64;ApiParam() &#64;RequestParam(required = false) String address,
    &#64;ApiParam() &#64;RequestParam(required = false) String addressLike,
    &#64;ApiParam() &#64;RequestParam(required = false) String avatarImgId,
    &#64;ApiParam() &#64;RequestParam(required = false, name="avatarImgIds") ArrayList&lt;String&gt; avatarImgIds,
    &#64;ApiParam() &#64;RequestParam(required = false) String email,
    &#64;ApiParam() &#64;RequestParam(required = false) String emailLike,
    &#64;ApiParam() &#64;RequestParam(required = false) Date valiDatetimeMin,
    &#64;ApiParam() &#64;RequestParam(required = false) Date valiDatetimeMax,
    &#64;ApiParam() &#64;RequestParam(required = false) Date birthdayDateMin,
    &#64;ApiParam() &#64;RequestParam(required = false) Date birthdayDateMax,
    &#64;ApiParam() &#64;RequestParam(required = false) Date workTimeMin,
    &#64;ApiParam() &#64;RequestParam(required = false) Date workTimeMax,
    &#64;ApiParam() &#64;RequestParam(required = false) String provinceId,
    &#64;ApiParam() &#64;RequestParam(required = false, name="provinceIds") ArrayList&lt;String&gt; provinceIds,
    &#64;ApiParam() &#64;RequestParam(required = false) String cityId,
    &#64;ApiParam() &#64;RequestParam(required = false, name="cityIds") ArrayList&lt;String&gt; cityIds,
    &#64;ApiParam() &#64;RequestParam(required = false) StatusEnum status,
    &#64;ApiParam() &#64;RequestParam(required = false, name="statuss") ArrayList&lt;StatusEnum&gt; statuss,
    &#64;ApiParam() &#64;RequestParam(required = false) Long grade,
    &#64;ApiParam() &#64;RequestParam(required = false) Long gradeMin,
    &#64;ApiParam() &#64;RequestParam(required = false) Long gradeMax,
    &#64;ApiParam() &#64;RequestParam(required = false) Long postAddressId,
    &#64;ApiParam() &#64;RequestParam(required = false, name="postAddressIds") ArrayList&lt;Long&gt; postAddressIds,
    &#64;ApiParam() &#64;RequestParam(required = false) Date updateTimeMin,
    &#64;ApiParam() &#64;RequestParam(required = false) Date updateTimeMax,
    &#64;ApiParam() &#64;RequestParam(required = false) Date createTimeMin,
    &#64;ApiParam() &#64;RequestParam(required = false) Date createTimeMax
    ,&#64;ApiParam(hidden = true) User user
    ,Pagination pagination
    </pre>
	 * 
	 * sql:select a.user_id, a.username, a.password, a.role_type, a.name, a.nickName, a.inter_code, a.mobile, a.age, a.address, a.avatar_img_id, a.email, a.vali_datetime, a.birthday_date, a.work_time, a.province_id, a.city_id, a.status, a.grade, a.sex, a.post_address_id, a.remark, a.update_time, a.create_time, a.delete_flag from user a where a.delete_flag = 0 and a.user_id=? and a.user_id in ( ? ) and a.username=? and a.username like CONCAT('%',?,'%') and a.password=? and a.password like CONCAT('%',?,'%') and a.role_type=? and a.role_type in ( ? ) and a.name=? and a.name like CONCAT('%',?,'%') and a.nickName=? and a.nickName like CONCAT('%',?,'%') and a.inter_code=? and a.inter_code like CONCAT('%',?,'%') and a.mobile=? and a.mobile like CONCAT('%',?,'%') and a.age=? and a.age >=? and a.age <? and a.address=? and a.address like CONCAT('%',?,'%') and a.avatar_img_id=? and a.avatar_img_id in ( ? ) and a.email=? and a.email like CONCAT('%',?,'%') and a.vali_datetime >=? and a.vali_datetime <? and a.birthday_date >=? and a.birthday_date <? and a.work_time >=? and a.work_time <? and a.province_id=? and a.province_id in ( ? ) and a.city_id=? and a.city_id in ( ? ) and a.status=? and a.status in ( ? ) and a.grade=? and a.grade >=? and a.grade <? and a.post_address_id=? and a.post_address_id in ( ? ) and a.update_time >=? and a.update_time <? and a.create_time >=? and a.create_time <? and 0 = 1 order by a.update_time desc, a.create_time desc
	 */
	public PageList<User> getPageList(User user, int pageSize, int pageNum) throws DataAccessException;
	
	/**
    <pre>
    &#64;ApiParam("用户ID") &#64;RequestParam(required = false, name="userIds") ArrayList&lt;String&gt; userIds    
    </pre>
	 * 
	 * sql:select a.user_id, a.username, a.password, a.role_type, a.name, a.nickName, a.inter_code, a.mobile, a.age, a.address, a.avatar_img_id, a.email, a.vali_datetime, a.birthday_date, a.work_time, a.province_id, a.city_id, a.status, a.grade, a.sex, a.post_address_id, a.remark, a.update_time, a.create_time, a.delete_flag from user a where a.delete_flag = 0 and 1=0 and a.user_id in ( ? ) order by a.update_time desc, a.create_time desc
	 */
	public List<User> getUsersByUserIds(java.util.List<String> userIds) throws DataAccessException;
	
	/**
    <pre>
    &#64;ApiParam("用户名") &#64;RequestParam(required = false, name="usernames") ArrayList&lt;String&gt; usernames    
    </pre>
	 * 
	 * sql:select a.user_id, a.username, a.password, a.role_type, a.name, a.nickName, a.inter_code, a.mobile, a.age, a.address, a.avatar_img_id, a.email, a.vali_datetime, a.birthday_date, a.work_time, a.province_id, a.city_id, a.status, a.grade, a.sex, a.post_address_id, a.remark, a.update_time, a.create_time, a.delete_flag from user a where a.delete_flag = 0 and 1=0 and a.username in ( ? ) order by a.update_time desc, a.create_time desc
	 */
	public List<User> getUsersByUsernames(java.util.List<String> usernames) throws DataAccessException;
	
	/**
    <pre>
    &#64;ApiParam("邮箱") &#64;RequestParam(required = false, name="emails") ArrayList&lt;String&gt; emails    
    </pre>
	 * 
	 * sql:select a.user_id, a.username, a.password, a.role_type, a.name, a.nickName, a.inter_code, a.mobile, a.age, a.address, a.avatar_img_id, a.email, a.vali_datetime, a.birthday_date, a.work_time, a.province_id, a.city_id, a.status, a.grade, a.sex, a.post_address_id, a.remark, a.update_time, a.create_time, a.delete_flag from user a where a.delete_flag = 0 and 1=0 and a.email in ( ? ) order by a.update_time desc, a.create_time desc
	 */
	public List<User> getUsersByEmails(java.util.List<String> emails) throws DataAccessException;
	
	/**
    <pre>
    &#64;ApiParam("用户ID") &#64;RequestParam(required = false, name="userIds") ArrayList&lt;String&gt; userIds    
    </pre>
	 * 
	 * sql:UPDATE user a SET a.delete_flag = 1 , a.update_time = CURRENT_TIMESTAMP(6) where a.delete_flag = 0 and 1=0 and a.user_id in ( ? )
	 */
	public java.util.List<String> deleteByUserIds(java.util.List<String> userIds) throws DataAccessException;
	
	/**
    <pre>
    &#64;ApiParam("用户名") &#64;RequestParam(required = false, name="usernames") ArrayList&lt;String&gt; usernames    
    </pre>
	 * 
	 * sql:UPDATE user a SET a.delete_flag = 1 , a.update_time = CURRENT_TIMESTAMP(6) where a.delete_flag = 0 and 1=0 and a.username in ( ? )
	 */
	public Long deleteByUsernames(java.util.List<String> usernames) throws DataAccessException;
	
	/**
    <pre>
    &#64;ApiParam("邮箱") &#64;RequestParam(required = false, name="emails") ArrayList&lt;String&gt; emails    
    </pre>
	 * 
	 * sql:UPDATE user a SET a.delete_flag = 1 , a.update_time = CURRENT_TIMESTAMP(6) where a.delete_flag = 0 and 1=0 and a.email in ( ? )
	 */
	public Long deleteByEmails(java.util.List<String> emails) throws DataAccessException;
	
	/**
    <pre>
    &#64;ApiParam("国际区号") &#64;RequestParam(required = false, name="interCodeList") ArrayList&lt;String&gt; interCodeList,
    &#64;ApiParam("手机号") &#64;RequestParam(required = false, name="mobiles") ArrayList&lt;String&gt; mobiles    
    </pre>
	 * 演示in的简单写法
	 * sql:select a.user_id, a.username, a.password, a.role_type, a.name, a.nickName, a.inter_code, a.mobile, a.age, a.address, a.avatar_img_id, a.email, a.vali_datetime, a.birthday_date, a.work_time, a.province_id, a.city_id, a.status, a.grade, a.sex, a.post_address_id, a.remark, a.create_time, a.update_time, a.delete_flag from user a where a.delete_flag = 0 and a.inter_code in ( ? ) and a.mobile in ( ? )
	 */
	public User getUserInMobiles(java.util.List<String> interCodeList, java.util.List<String> mobiles) throws DataAccessException;
	

}



