spring:
  cloud:
    stream:
      function:
        definition: supplier;receive1;receive2;
      bindings:
        receive1-in-0:
          destination: customerId-1
#          group: customerId-1-group
        receive2-in-0:
          destination: customerId-2
#          group: customerId-2-group