#　　–file:./config/ > 　–file:./ > –classpath:/config/ >　–classpath:/
spring:
  cloud:
    stream:
      function:
        definition: supplier;receiveTrade;
      bindings:
        receiveTrade-in-0:
          destination: receiveTrade-dest
          group: receiveTrade-group