/*
 * Do not remove this unless you get business authorization.
 * Copyright (c) 2016 - 2018 All Rights Reserved.
 * Powered By [stategen.dalgen]
 */
package com.mycompany.biz.service.impl;

import java.util.Collection;
import java.util.List;
import java.util.function.BiConsumer;
import java.util.function.Function;
import javax.annotation.Resource;

import org.stategen.framework.lite.IIdGenerator;
import org.stategen.framework.lite.IdGenerateService;
import org.stategen.framework.lite.PageList;
import org.stategen.framework.util.ServiceUtil;
import org.stategen.framework.util.StringUtil;

import com.mycompany.biz.dao.CategorySubDao;
import com.mycompany.biz.domain.CategorySub;
import com.mycompany.biz.service.CategorySubService;

/**
 * CategorySubServiceImpl
 * <pre>
 * database table: category_sub
 * database table comments: CategorySub
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 *
 * 新生成的类中的方法，只有在不同名的情况下才会被追加到该类下，
 * 因此该类可以修改任何部分
 * </pre>
 */
public class CategorySubServiceImpl implements CategorySubService, IdGenerateService<String> {

    @Resource
    private IIdGenerator idGenerator;

    @Resource(name = "categorySubDao")
    CategorySubDao categorySubDao;

    /**
     * 
     * @see com.mycompany.biz.dao.CategorySubDao#insert
     * @see com.mycompany.biz.service.CategorySubService#insert
     */
    @Override
    public CategorySub insert(CategorySub categorySub) {
        return categorySubDao.insert(categorySub, this);
    }

    /**
     * 
     * @see com.mycompany.biz.dao.CategorySubDao#delete
     * @see com.mycompany.biz.service.CategorySubService#delete
     */
    @Override
    public String delete(String mallSubId) {
        return categorySubDao.delete(mallSubId);
    }

    /**
     * 
     * @see com.mycompany.biz.dao.CategorySubDao#update
     * @see com.mycompany.biz.service.CategorySubService#update
     */
    @Override
    public CategorySub update(CategorySub categorySub) {
        return categorySubDao.update(categorySub);
    }

    /*** 保存categorySub,有id时更新，没有id时插入,并带回新的id，返回 categorySub*/
    @Override
    public CategorySub saveCategorySub(CategorySub categorySub) {
        if (categorySub != null) {
            java.lang.String mallSubId = categorySub.getCategorySubId();
            if (StringUtil.isBlank(mallSubId)) {
                insert(categorySub);
            } else {
                update(categorySub);
            }
        }
        return categorySub;
    }

    /*** 批量保存categorySubs,有id时更新，没有id时插入,并带回新的id，返回 categorySubs*/
    @Override
    public List<CategorySub> saveCategorySubs(List<CategorySub> categorySubs) {
        for (CategorySub categorySub : categorySubs) {
            this.saveCategorySub(categorySub);
        }
        return categorySubs;
    }

    /**
     * 
     * @see com.mycompany.biz.dao.CategorySubDao#getPageList
     * @see com.mycompany.biz.service.CategorySubService#getPageList
     */
    @Override
    public PageList<CategorySub> getPageList(CategorySub categorySub, int pageSize, int pageNum) {
        return categorySubDao.getPageList(categorySub, pageSize, pageNum);
    }

    @Override
    public <D> void assignBeanTo(Collection<D> dests, Function<? super D, String> destGetMethod, BiConsumer<D, CategorySub> destSetMethod) {
        ServiceUtil.interalAssignBeanTo(dests, destGetMethod, destSetMethod, this, CategorySubServiceImpl::getCategorySubsByCategorySubIds, CategorySub::getCategorySubId);
    }

    @Override
    public <D, G> void assignBeansTo(Collection<D> dests, Function<? super D, G> destGetMethod, BiConsumer<D, List<CategorySub>> destSetMethod, BiConsumer<CategorySub, List<G>> resultSetQueryIdsFun, Function<? super CategorySub, G> resultGetGoupIdFun) {
        ServiceUtil.interalAssignBeansTo(dests, destGetMethod, destSetMethod, this, new CategorySub(), resultSetQueryIdsFun, resultGetGoupIdFun, 100);
    }

    @Override
    public <D> void mergeBeanTo(Collection<D> dests, Function<? super D, String> destGetMethod) {
        ServiceUtil.interalMergeBeanTo(dests, destGetMethod, this, CategorySubServiceImpl::getCategorySubsByCategorySubIds, CategorySub::getCategorySubId);
    }

    /**
     * 
     * @see com.mycompany.biz.dao.CategorySubDao#getCategorySubByCategorySubId
     * @see com.mycompany.biz.service.CategorySubService#getCategorySubByCategorySubId
     */
    @Override
    public CategorySub getCategorySubByCategorySubId(String categorySubId) {
        return categorySubDao.getCategorySubByCategorySubId(categorySubId);
    }

    /**
     * 
     * @see com.mycompany.biz.dao.CategorySubDao#getCategorySubsByCategorySubIds
     * @see com.mycompany.biz.service.CategorySubService#getCategorySubsByCategorySubIds
     */
    @Override
    public List<CategorySub> getCategorySubsByCategorySubIds(java.util.List<String> categorySubIds) {
        return categorySubDao.getCategorySubsByCategorySubIds(categorySubIds);
    }

    /**
     * 
     * @see com.mycompany.biz.dao.CategorySubDao#deleteByCategorySubIds
     * @see com.mycompany.biz.service.CategorySubService#deleteByCategorySubIds
     */
    @Override
    public java.util.List<String> deleteByCategorySubIds(java.util.List<String> categorySubIds) {
        return categorySubDao.deleteByCategorySubIds(categorySubIds);
    }

    @Override
    public <T> String generateId(Class<T> bizTagClz) {
        return this.idGenerator.generateId(String.class, bizTagClz);
    }
}
