/*
 * Do not remove this unless you get business authorization.
 * Copyright (c) 2016 - 2018 All Rights Reserved.
 * Powered By [stategen.dalgen]
 */
package com.mycompany.biz.service.impl;

import java.util.Collection;
import java.util.List;
import java.util.function.BiConsumer;
import java.util.function.Function;
import javax.annotation.Resource;

import org.stategen.framework.lite.IIdGenerator;
import org.stategen.framework.lite.IdGenerateService;
import org.stategen.framework.lite.PageList;
import org.stategen.framework.util.ServiceUtil;
import org.stategen.framework.util.StringUtil;

import com.mycompany.biz.dao.CityDao;
import com.mycompany.biz.domain.City;
import com.mycompany.biz.service.CityService;

/**
 * CityServiceImpl
 * <pre>
 * database table: city
 * database table comments: City
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 *
 * 新生成的类中的方法，只有在不同名的情况下才会被追加到该类下，
 * 因此该类可以修改任何部分
 * </pre>
 */
public class CityServiceImpl implements CityService, IdGenerateService<String> {

    @Resource
    private IIdGenerator idGenerator;

    //<#--
    @Resource(name = "cityDao")
    CityDao cityDao;

    /**
     * 
     * @see com.mycompany.biz.dao.CityDao#insert
     * @see com.mycompany.biz.service.CityService#insert
     */
    @Override
    public City insert(City city) {
        return cityDao.insert(city, this);
    }

    /**
     * 
     * @see com.mycompany.biz.dao.CityDao#delete
     * @see com.mycompany.biz.service.CityService#delete
     */
    @Override
    public String delete(String cityId) {
        return cityDao.delete(cityId);
    }

    /**
     * 
     * @see com.mycompany.biz.dao.CityDao#update
     * @see com.mycompany.biz.service.CityService#update
     */
    @Override
    public City update(City city) {
        return cityDao.update(city);
    }

    /**
     * 
     * @see com.mycompany.biz.dao.CityDao#getCityByCityId
     * @see com.mycompany.biz.service.CityService#getCityByCityId
     */
    @Override
    public City getCityByCityId(String cityId) {
        return cityDao.getCityByCityId(cityId);
    }

    /**
     * 
     * @see com.mycompany.biz.dao.CityDao#getCitysByCityIds
     * @see com.mycompany.biz.service.CityService#getCitysByCityIds
     */
    @Override
    public List<City> getCitysByCityIds(java.util.List<String> cityIds) {
        return cityDao.getCitysByCityIds(cityIds);
    }

    /**
     * 
     * @see com.mycompany.biz.dao.CityDao#deleteByCityIds
     * @see com.mycompany.biz.service.CityService#deleteByCityIds
     */
    @Override
    public java.util.List<String> deleteByCityIds(java.util.List<String> cityIds) {
        return cityDao.deleteByCityIds(cityIds);
    }

    /*** 保存city,有id时更新，没有id时插入,并带回新的id，返回 city*/
    @Override
    public City saveCity(City city) {
        if (city != null) {
            java.lang.String cityId = city.getCityId();
            if (StringUtil.isBlank(cityId)) {
                insert(city);
            } else {
                update(city);
            }
        }
        return city;
    }

    /*** 批量保存citys,有id时更新，没有id时插入,并带回新的id，返回 citys*/
    @Override
    public List<City> saveCitys(List<City> citys) {
        for (City city : citys) {
            this.saveCity(city);
        }
        return citys;
    }

    /**
     * 
     * @see com.mycompany.biz.dao.CityDao#getCityOptions
     * @see com.mycompany.biz.service.CityService#getCityOptions
     */
    @Override
    public List<City> getCityOptions(String provinceId) {
        return cityDao.getCityOptions(provinceId);
    }

    /**
     * 
     * @see com.mycompany.biz.dao.CityDao#getPageList
     * @see com.mycompany.biz.service.CityService#getPageList
     */
    @Override
    public PageList<City> getPageList(City city, int pageSize, int pageNum) {
        return cityDao.getPageList(city, pageSize, pageNum);
    }

    //-->
    //
    @Override
    public <D> void assignBeanTo(Collection<D> dests, Function<? super D, String> destGetMethod, BiConsumer<D, City> destSetMethod) {
        ServiceUtil.interalAssignBeanTo(dests, destGetMethod, destSetMethod, this, CityServiceImpl::getCitysByCityIds, City::getCityId);
    }

    @Override
    public <D, G> void assignBeansTo(Collection<D> dests, Function<? super D, G> destGetMethod, BiConsumer<D, List<City>> destSetMethod, BiConsumer<City, List<G>> resultSetQueryIdsFun, Function<? super City, G> resultGetGoupIdFun) {
        ServiceUtil.interalAssignBeansTo(dests, destGetMethod, destSetMethod, this, new City(), resultSetQueryIdsFun, resultGetGoupIdFun, 100);
    }

    @Override
    public <D> void mergeBeanTo(Collection<D> dests, Function<? super D, String> destGetMethod) {
        ServiceUtil.interalMergeBeanTo(dests, destGetMethod, this, CityServiceImpl::getCitysByCityIds, City::getCityId);
    }

    @Override
    public <T> String generateId(Class<T> bizTagClz) {
        return this.idGenerator.generateId(String.class, bizTagClz);
    }
}
