/*
 * Copyright (c) 2016 - 2116 All Rights Reserved.
 * Powered By [rapid-generator]
 */
package com.mycompany.biz.service.impl;

import java.util.List;
import java.util.Map;
import javax.annotation.Resource;

import org.stategen.framework.lite.PageList;
import org.stategen.framework.util.CollectionUtil;
import org.stategen.framework.util.StringUtil;

import com.mycompany.biz.dao.RoleDao;
import com.mycompany.biz.domain.Menu;
import com.mycompany.biz.domain.Role;
import com.mycompany.biz.domain.RoleMenu;
import com.mycompany.biz.service.MenuService;
import com.mycompany.biz.service.RoleMenuService;
import com.mycompany.biz.service.RoleService;

/**
 * RoleServiceImpl
 * <pre>
 * database table: role
 * database table comments: Role
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 *
 * 新生成的类中的方法，只有在不同名的情况下才会被追加到该类下，
 * 因此该类可以修改任何部分
 * </pre>
 */
public class RoleServiceImpl implements RoleService {

    @Resource(name = "roleDao")
    RoleDao roleDao;

    @Resource
    MenuService menuService;

    @Resource
    RoleMenuService roleMenuService;

    /*** 保存role,有id时更新，没有id时插入，返回 role*/
    public Role saveRole(Role role) {
        if (role != null) {
            java.lang.String roleId = role.getRoleId();
            if (StringUtil.isBlank(roleId)) {
                insert(role);
            } else {
                update(role);
            }
        }
        return role;
    }

    /*** 批量保存roles,有id时更新，没有id时插入,并带回新的id，返回 roles*/
    @Override
    public List<Role> saveRoles(List<Role> roles) {
        for (Role role : roles) {
            this.saveRole(role);
        }
        return roles;
    }

    @Override
    public List<Menu> getAllMenusWithRoleChecked(String roleId) {
        List<Menu> menus = this.menuService.getMenusByProjectName(menuService.getProjectName());
        List<Long> menuIds = CollectionUtil.toList(menus, Menu::getMenuId);
        List<RoleMenu> roleMenus = this.roleMenuService.getRoleMenusByMenuIds(menuIds);
        Map<Long, RoleMenu> menuIdRoleMenuMap = CollectionUtil.toMap(roleMenus, RoleMenu::getMenuId);
        for (Menu menu : menus) {
            menu.setRoleId(roleId);
            Long menuId = menu.getMenuId();
            menu.setChecked(menuIdRoleMenuMap.containsKey(menuId));
        }
        return menus;
    }

    /**
     * 
     * @see com.mycompany.biz.dao.RoleDao#insert
     * @see com.mycompany.biz.service.RoleService#insert
     */
    @Override
    public Role insert(Role role) {
        return roleDao.insert(role);
    }

    /**
     * 
     * @see com.mycompany.biz.dao.RoleDao#deleteByRoleId
     * @see com.mycompany.biz.service.RoleService#deleteByRoleId
     */
    @Override
    public Long deleteByRoleId(String roleId) {
        return roleDao.deleteByRoleId(roleId);
    }

    /**
     * 
     * @see com.mycompany.biz.dao.RoleDao#update
     * @see com.mycompany.biz.service.RoleService#update
     */
    @Override
    public Role update(Role role) {
        return roleDao.update(role);
    }

    /**
     * 
     * @see com.mycompany.biz.dao.RoleDao#getRoleByRoleId
     * @see com.mycompany.biz.service.RoleService#getRoleByRoleId
     */
    @Override
    public Role getRoleByRoleId(String roleId) {
        return roleDao.getRoleByRoleId(roleId);
    }

    /**
     * 
     * @see com.mycompany.biz.dao.RoleDao#getRolePageList
     * @see com.mycompany.biz.service.RoleService#getRolePageList
     */
    @Override
    public PageList<Role> getRolePageList(int pageSize, int pageNum) {
        return roleDao.getRolePageList(pageSize, pageNum);
    }

    /**
     * 
     * @see com.mycompany.biz.dao.RoleDao#getRolePageListByDefaultQuery
     * @see com.mycompany.biz.service.RoleService#getRolePageListByDefaultQuery
     */
    @Override
    public PageList<Role> getRolePageListByDefaultQuery(Role role, int pageSize, int pageNum) {
        return roleDao.getRolePageListByDefaultQuery(role, pageSize, pageNum);
    }

    /**
     * 
     * @see com.mycompany.biz.dao.RoleDao#getRolesByRoleIds
     * @see com.mycompany.biz.service.RoleService#getRolesByRoleIds
     */
    @Override
    public List<Role> getRolesByRoleIds(java.util.List<String> roleIds) {
        return roleDao.getRolesByRoleIds(roleIds);
    }

    /**
     * 
     * @see com.mycompany.biz.dao.RoleDao#batchDelete
     * @see com.mycompany.biz.service.RoleService#batchDelete
     */
    @Override
    public Long batchDelete(java.util.List<String> roleIds) {
        return roleDao.batchDelete(roleIds);
    }

    /**
     * 
     * @see com.mycompany.biz.dao.RoleDao#getAllRoles
     * @see com.mycompany.biz.service.RoleService#getAllRoles
     */
    @Override
    public List<Role> getAllRoles() {
        return roleDao.getAllRoles();
    }
}
