/*
 * Do not remove this unless you get business authorization.
 * Copyright (c) 2016 - 2018 All Rights Reserved.
 * Powered By [stategen.dalgen]
 */
package com.mycompany.biz.service.impl;

import java.util.Arrays;
import java.util.List;
import javax.annotation.Resource;

import org.stategen.framework.lite.PageList;
import org.stategen.framework.util.CollectionUtil;
import org.stategen.framework.util.StringUtil;

import com.mycompany.biz.dao.TopicDao;
import com.mycompany.biz.domain.Topic;
import com.mycompany.biz.domain.TopicReply;
import com.mycompany.biz.domain.User;
import com.mycompany.biz.service.TopicReplyService;
import com.mycompany.biz.service.TopicService;
import com.mycompany.biz.service.UserService;

/**
 * TopicServiceImpl
 * <pre>
 * database table: topic
 * database table comments: Topic
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 *
 * 新生成的类中的方法，只有在不同名的情况下才会被追加到该类下，
 * 因此该类可以修改任何部分
 * </pre>
 */
public class TopicServiceImpl implements TopicService {

    @Resource(name = "topicDao")
    TopicDao topicDao;

    @Resource
    UserService userService;

    @Resource
    TopicReplyService topicReplyService;

    /**
     * 
     * @see com.mycompany.biz.dao.TopicDao#insert
     * @see com.mycompany.biz.service.TopicService#insert
     */
    @Override
    public Topic insert(Topic topic) {
        return topicDao.insert(topic);
    }

    /**
     * 
     * @see com.mycompany.biz.dao.TopicDao#delete
     * @see com.mycompany.biz.service.TopicService#delete
     */
    @Override
    public String delete(String topicId) {
        return topicDao.delete(topicId);
    }

    /**
     * 
     * @see com.mycompany.biz.dao.TopicDao#update
     * @see com.mycompany.biz.service.TopicService#update
     */
    @Override
    public Topic update(Topic topic) {
        return topicDao.update(topic);
    }

    /**
     * 
     * @see com.mycompany.biz.dao.TopicDao#getTopicByTopicId
     * @see com.mycompany.biz.service.TopicService#getTopicByTopicId
     */
    @Override
    public Topic getTopicByTopicId(String topicId) {
        Topic topic = topicDao.getTopicByTopicId(topicId);
        setTopicsAuthor(Arrays.asList(topic));
        setTopicsReplies(Arrays.asList(topic));
        return topic;
    }

    private void setTopicsReplies(List<Topic> topics) {
        List<String> topicIds = CollectionUtil.toList(topics, Topic::getTopicId);
        TopicReply topicReply = new TopicReply();
        topicReply.setTopicIds(topicIds);
        PageList<TopicReply> topicReplyPageList = this.topicReplyService.getTopicReplyPageListByDefaultQuery(topicReply, 2000, 1);
        CollectionUtil.setListByList(topics, topicReplyPageList.getItems(), Topic::getTopicId, Topic::setReplies, TopicReply::getTopicId);
    }

    /**
     * 
     * @see com.mycompany.biz.dao.TopicDao#getTopicPageListByDefaultQuery
     * @see com.mycompany.biz.service.TopicService#getTopicPageListByDefaultQuery
     */
    @Override
    public PageList<Topic> getTopicPageListByDefaultQuery(Topic topic, int pageSize, int pageNum) {
        PageList<Topic> topicPageList = topicDao.getTopicPageListByDefaultQuery(topic, pageSize, pageNum);
        List<Topic> items = topicPageList.getItems();
        setTopicsAuthor(items);
        return topicPageList;
    }

    private void setTopicsAuthor(List<Topic> topics) {
        List<String> authorIds = CollectionUtil.toList(topics, Topic::getAuthorId);
        List<User> topicAuthors = userService.getUsersByUserIds(authorIds);
        CollectionUtil.setModelByList(topics, topicAuthors, Topic::getAuthorId, Topic::setAuthor, User::getUserId);
    }

    /**
     * 
     * @see com.mycompany.biz.dao.TopicDao#getTopicsByTopicIds
     * @see com.mycompany.biz.service.TopicService#getTopicsByTopicIds
     */
    @Override
    public List<Topic> getTopicsByTopicIds(java.util.List<String> topicIds) {
        return topicDao.getTopicsByTopicIds(topicIds);
    }

    /**
     * 
     * @see com.mycompany.biz.dao.TopicDao#deleteByTopicIds
     * @see com.mycompany.biz.service.TopicService#deleteByTopicIds
     */
    @Override
    public java.util.List<String> deleteByTopicIds(java.util.List<String> topicIds) {
        return topicDao.deleteByTopicIds(topicIds);
    }

    /*** 保存topic,有id时更新，没有id时插入,并带回新的id，返回 topic*/
    @Override
    public Topic saveTopic(Topic topic) {
        if (topic != null) {
            java.lang.String topicId = topic.getTopicId();
            if (StringUtil.isBlank(topicId)) {
                insert(topic);
            } else {
                update(topic);
            }
        }
        return topic;
    }

    /*** 批量保存topics,有id时更新，没有id时插入,并带回新的id，返回 topics*/
    @Override
    public List<Topic> saveTopics(List<Topic> topics) {
        for (Topic topic : topics) {
            this.saveTopic(topic);
        }
        return topics;
    }
}
